#!/bin/bash

if [ -z $3 ]
then
    echo Usage: install project-name username password
    exit 1
fi

echo Installing project $1...

ddev config --project-name=$1
ddev composer install &&
ddev composer run setup &&
ddev artisan app:create-first-user $2 $3 admin@example.com &&
ddev describe &&
ddev launch
